# Part 1

The file "Purchase_Data.csv" contains purchase data at a Chinese supermarket for various products.  Read this csv into a dataframe called df_data and use the head() method to check that you have read in the data correctly. Make sure you import pandas.

In [97]:
import pandas as pd

df_data = pd.read_csv("data/purchase_data.csv")
df_data.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0

Use the dtypes attribute to view how each column is stored

In [98]:
df_data.dtypes

invoice_number    float64
invoice_time       object
store_id           object
product_id          int64
category_id         int64
num_item          float64
price             float64
dtype: object

Slice the first two columns using .loc and store the result in a variable called result_1.

In [99]:
result_1 = df_data.loc[:, df_data.columns[:2]]
result_1.head()

   invoice_number   invoice_time
0    2.020000e+11  7/15/15 10:45
1    2.020000e+11  7/15/15 12:16
2    2.020000e+11  7/15/15 12:16
3    2.020000e+11  7/15/15 12:16
4    2.020000e+11  7/15/15 12:16

Slice the first two rows using .loc and store the result in a variable called result_2.

In [100]:
result_2 = df_data.loc[:1]
result_2.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0

Slice the first four rows and the first five columns and store the result in a variable called result_3.

In [101]:
result_3 = df_data.iloc[:4, :5]
result_3.head()

   invoice_number   invoice_time store_id  product_id  category_id
0    2.020000e+11  7/15/15 10:45     G816     7000300       210101
1    2.020000e+11  7/15/15 12:16     G816     7070884        70203
2    2.020000e+11  7/15/15 12:16     G816     7070884        70203
3    2.020000e+11  7/15/15 12:16     G816     7070891        70401

Slice rows 0,4,6 and columns invoice time and price and store the result in variable called result_4.

In [102]:
df_data.columns

Index(['invoice_number', 'invoice_time', 'store_id', 'product_id',
       'category_id', 'num_item', 'price'],
      dtype='object')

In [103]:
result_4 = df_data.loc[[0,4,6], ['invoice_time' , 'price']]
result_4.head()

    invoice_time  price
0  7/15/15 10:45    2.0
4  7/15/15 12:16    6.0
6  7/15/15 15:28    2.0

Store the number rows in a variable called num_rows.

In [104]:
num_rows = len(df_data)
num_rows

5382

Print out the last row of the data to dataframe. **Hint:** use the variable num_rows from the previous exercise.

In [105]:
last_row = df_data.loc[num_rows - 1]
last_row

invoice_number    202000000000.0
invoice_time        9/5/15 23:38
store_id                    G619
product_id              23030206
category_id               210101
num_item                     1.0
price                        2.0
Name: 5381, dtype: object

# Part 2

Compute the average and max price charged.  Store the results in variables called avg_price and max_price

In [106]:
avg_price = df_data['price'].sum() / num_rows
print("average: ", avg_price)
max_price = df_data['price'].max()
print("maximum: ", max_price)

average:  3.1920522110741363
maximum:  6.01

Compute the average price and average number of items purchased with only a single call to the mean() method. Store these averages in avg_price and avg_num_items.

In [107]:
avg_price, avg_num_items = df_data[["price", "num_item"]].mean()    
print("average price: ", avg_price)
print("average number of items: ", avg_num_items)

average price:  3.1920522110741363
average number of items:  1.2983091787439613

Create a column called "total", which is the product of the price and num_item columns.

In [108]:
df_data["total"] = df_data["price"] * df_data["num_item"]
print("total: ", f"{df_data['total'].sum():.2f}")

total:  21160.99

What is the avgerage price of the three most expensive purchases?

In [109]:
df_data["price"].nlargest(3).mean()

np.float64(6.003333333333333)

How many different products are there?

In [110]:
print(df_data["product_id"].nunique())

53

Find the difference between the mean and median of the column total.  Use the describe() method and then index the dataframe it returns.

In [111]:
stats = df_data["total"].describe()
diff = stats["mean"] - stats["50%"]
print("Difference between mean and median:", diff)

Difference between mean and median: 0.9318078781127839

Use the drop() method to delete the column total from the dataframe df_data.

In [112]:
df_data.drop(columns=["total"], inplace=True)

Let's dig a little deeper into the data set and answer some basic question.

In [113]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5382 entries, 0 to 5381
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_number  5382 non-null   float64
 1   invoice_time    5382 non-null   object
 2   store_id        5382 non-null   object
 3   product_id      5382 non-null   int64
 4   category_id     5382 non-null   int64
 5   num_item        5382 non-null   float64
 6   price           5382 non-null   float64
dtypes: float64(3), int64(2), object(2)
memory usage: 294.5+ KB

First, covert the column invoice time to a datetime column. Print out the new column types to make sure this was done correctly

In [114]:
df_data['invoice_time'] = pd.to_datetime(df_data["invoice_time"])
df_data.dtypes

C:\Users\LAPTOP\AppData\Local\Temp\ipykernel_15160\2097801500.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_data['invoice_time'] = pd.to_datetime(df_data["invoice_time"])

invoice_number           float64
invoice_time      datetime64[ns]
store_id                  object
product_id                 int64
category_id                int64
num_item                 float64
price                    float64
dtype: object

Next, let's create columns called "DOW" and "Month", which store the corresponding weekday and month of the invoice respectively.  Print the head of the dataframe to make sure this was done correctly.

In [115]:
df_data['DOW'] = df_data['invoice_time'].dt.day_name()
df_data['Month'] = df_data['invoice_time'].dt.month_name()
df_data[['DOW', 'Month']]

            DOW      Month
0     Wednesday       July
1     Wednesday       July
2     Wednesday       July
3     Wednesday       July
4     Wednesday       July
...         ...        ...
5377   Saturday  September
5378   Saturday  September
5379   Saturday  September
5380   Saturday  September
5381   Saturday  September

[5382 rows x 2 columns]

Create a variable called num_purchases_wed, which stores the number of purchases made on Wednesday?  You should use value_counts and then index the series it return.

In [116]:
num_purchases_wed = df_data["DOW"].value_counts()["Wednesday"]
print(num_purchases_wed)

959

# Part 3

In this set of practice exercises, we will be working with a demographic data regarding the passengers aboard the Titanic.  Read in the data frame and use the head() method to check that it was read in correctly.

In [117]:
df_titanic = pd.read_csv('Data/titanic.csv')
df_titanic.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Use the rename method to change the column "Name" to "Passenger_Name" and the column "Ticket" to "Ticket_Num".

In [118]:
df_titanic = df_titanic.rename(
    columns={"Name": "Passenger_Name", "Ticket": "Ticket_Num"}
)
df_titanic.head()

,PassengerId,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Change the index of the df_titanic to the column PasengerID.

In [119]:
df_titanic = df_titanic.set_index("PassengerId")
df_titanic.head()

,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,
892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Select the name of passenger 896

In [120]:
df_titanic.loc[896, "Passenger_Name"]

'Hirvonen, Mrs. Alexander (Helga E Lindqvist)'

Change the index back to row numbers but making sure that we don't lose the PassengerId column.

In [121]:
df_titanic = df_titanic.reset_index()
if "index" in df_titanic.columns:
    df_titanic = df_titanic.drop(columns=["index"])
df_titanic.head()

,PassengerId,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

How many missing entries are there in the Age column? Use the isnull() method and recall than Booleans are exactly like 1s (True) and 0s (False).

In [122]:
print(df_titanic["Age"].isnull().sum())

86

What is the average age of the 5 oldest passengers? The reset_index method will be helpful here.

Compute the avg age of passengers ignoring the missing data.

In [123]:
avg_age = df_titanic["Age"].mean()
avg_age

np.float64(30.272590361445783)

Using the fillna() method replace the missing values in the Age column with the mean.

In [124]:
df_titanic['Age'] = df_titanic['Age'].fillna(avg_age)
df_titanic.head()

,PassengerId,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

What is the average age of the 5 oldest passengers? The reset_index method will be helpful here.

In [125]:
avg_oldest_5 = df_titanic["Age"].nlargest(5).mean()
avg_oldest_5

np.float64(67.0)